version: "3.8"

services:
  app:
    build: .
    ports:
      - "10000:10000"
    depends_on:
      - redis
    environment:
      - PORT=10000

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
