"""init

Revision ID: 8e476d6973ba
Revises: 9a1c5b89765b
Create Date: 2025-03-21 19:17:37.542785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e476d6973ba'
down_revision: Union[str, None] = '9a1c5b89765b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('additional', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
   
    op.add_column('posts', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)



def downgrade() -> None:
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.alter_column('posts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('posts', 'organization_id')
   
  
    
    op.drop_table('organization_events')
    # ### end Alembic commands ###
